export const GET_ERROR = "GET_ERROR"
export const CREATE_PRODUCTS = "CREATE_PRODUCTS"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCT_DETALIS = "GET_PRODUCT_DETALIS"
export const DELETE_PRODUCTS = "DELETE_PRODUCTS"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"



export const ADD_TO_CART = "ADD_TO_CART"
export const GET_ALL_USER_CART = "GET_ALL_USER_CART"
export const CLEAR_ALL_USER_CART = "CLEAR_ALL_USER_CART"
export const DELETE_ITEM_FROMCART = "DELETE_ITEM_FROMCART"


